program: train.py
method: grid
metric:
  goal: minimize
  name: train_loss
parameters:
  data_directory:
    value: "./data_nuevo_canal/model_train/"
  optimizer:
    value: adam
  dropout:
    value: 0 
  update_coors: 
    value: False
  update_feats: 
    value: True  
  output_dims:
    values: [[2,2],[10,10], [32,32]]
  m_dims:
    values: [[10,10],[16, 16],[32,32]]
  learning_rate:
    values: [0.01, 0.05]
  batch_size: 
    values: [20,10,5]
  epochs:
    value: 3
  NormCoors:
    value: False
  aggr:
    values: ['mean','add']
